// Generated by CoffeeScript 1.10.0
(function() {
  var removeScripts, removeTags;

  removeTags = function(value) {
    return value.replace(/<\/?[^>]+(>|$)/g, '');
  };

  removeScripts = function(value) {
    return value.replace(/script|onblur|onchange|onclick|ondblclick|onfocus|onkeydown|onkeypress|onkeyup|onload|onmousedown|onmousemove|onmouseout|onmouseover|onmouseup|onreset|onselect|onsubmit|onunload/gi, '');
  };

  exports.removeTags = removeTags;

  exports.removeScripts = removeScripts;

}).call(this);

//# sourceMappingURL=utils.js.map
